name: CI

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        ruby: [ '3.3', '3.2', '3.1', '3.0', '2.7', '2.6', '2.5' ]
      fail-fast: false
    runs-on: ubuntu-latest
    name: ${{ matrix.ruby }}
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rspec

    env:
      BUNDLE_JOBS: 4
      BUNDLE_PATH: vendor/bundle
      CI: true
